ALTER TABLE "User" ADD COLUMN "first_name" TEXT NOT NULL DEFAULT 'Jasmine';
ALTER TABLE "User" ADD COLUMN "last_name" TEXT NOT NULL DEFAULT 'Valentine';

ALTER TABLE "User" ALTER COLUMN "first_name" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "last_name" DROP DEFAULT;
